plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.0' // Spring Boot H& 3.4.0!
    id 'io.spring.dependency-management' version '1.1.0'
}
group 'me.scpark'
version '1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21) // java oracle jdk 2:
    }
}
repositories {
    mavenCentral()
}
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}
test {
    useJUnitPlatform()
}