plugins {
    id 'java'
    id 'org.springframework.boot' version '3.4.0' // Spring Boot H& 3.4.0!
    id 'io.spring.dependency-management' version '1.1.0'
}
group 'me.scpark'
version '1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21) // java oracle jdk 2:
    }
}
repositories {
    mavenCentral()
}
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    implementation 'org.springframework.boot:spring-boot-starter-web'
    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    implementation 'org.springframework.boot:spring-boot-starter-data-jpa' // 스프링 데이터 JPA
    runtimeOnly 'com.h2database:h2' // 인메모리 데이터베이스
    compileOnly 'org.projectlombok:lombok' // 반복적인 메서드 작성 작업을 줄여주는 롬복
    annotationProcessor 'org.projectlombok:lombok'
}
test {
    useJUnitPlatform()
}
