INSERT INTO member (id, name) VALUES (1,'A')
INSERT INTO member (id, name) VALUES (2,'B')
INSERT INTO member (id, name) VALUES (3,'C')
INSERT INTO article (title, content) VALUES ('제목 1', '내용1')
INSERT INTO article (title, content) VALUES ('제목 2', '내용2')
INSERT INTO article (title, content) VALUES ('제목 3', '내용3')